SELECT 
	count(recid)
	--"PURCHID", "PACKINGSLIPID", "ORDERDATE", "ARRIVALDATE", "VENDORNO", "STATUS", "STATUSTEXT", "UNIQUEID", "MODIFIEDDATETIME", "MODIFIEDBY", "CREATEDDATETIME", "CREATEDBY", "DATAAREAID", "RECVERSION", "PARTITION", "RECID" 
FROM 
	"AX.PROD_DynamicsAX2012.dbo.WINPURCHORDERRECEIPTTABLESTAGING"
Where 
	arrivaldate between '2017-12-01' and '2017-12-31'	