Select 
	"CUSTOMERREF","SALESID","SALESNAME","CUSTACCOUNT","INVOICEACCOUNT","PURCHORDERFORMNUM","CURRENCYCODE","TAXGROUP","CUSTGROUP","DLVMODE","DELIVERYNAME","INVENTLOCATIONID","LANGUAGEID","SALESORIGINID","PAYMMODE","INVENTSITEID","SHIPCARRIERID"
From "AX.PROD_DynamicsAX2012.dbo.SalesTable"
Where "PURCHORDERFORMNUM" in 
('125170835284848000')